// Comprehensive list of possible body parts for tattoos (direction first)
export const spotSuggestionsEn = [
  // Head & Face
  "Forehead",
  "left temple",
  "right temple",
  "left cheek",
  "right cheek",
  "left ear",
  "right ear",
  "earlobe",
  "left jaw",
  "right jaw",
  "Chin",
  "Nose",
  "Eyebrow",
  "upper lip",
  "lower lip",
  "back of head",
  "Nape",

  // Neck & Collarbone
  "front of neck",
  "side of neck left",
  "side of neck right",
  "left collarbone",
  "right collarbone",
  "Larynx",
  "Cervical spine",

  // Chest & Abdomen
  "Chest",
  "left chest",
  "right chest",
  "under left breast",
  "under right breast",
  "Sternum",
  "Solar plexus",
  "Abdomen",
  "upper abdomen",
  "lower abdomen",
  "Navel",
  "side abdomen left",
  "side abdomen right",

  // Back
  "upper back",
  "middle back",
  "lower back",
  "left half of back",
  "right half of back",
  "Spine",
  "Coccyx",
  "left shoulder blade",
  "right shoulder blade",

  // Arms
  "outer left upper arm",
  "outer right upper arm",
  "inner left upper arm",
  "inner right upper arm",
  "outer left forearm",
  "outer right forearm",
  "inner left forearm",
  "inner right forearm",
  "left armpit",
  "right armpit",
  "left elbow",
  "right elbow",
  "left wrist",
  "right wrist",
  "left back of hand",
  "right back of hand",
  "left palm",
  "right palm",
  "left thumb",
  "right thumb",
  "all fingers",
  "left index finger",
  "left middle finger",
  "left ring finger",
  "left pinky finger",
  "right index finger",
  "right middle finger",
  "right ring finger",
  "right pinky finger",

  // Legs
  "outer left thigh",
  "outer right thigh",
  "inner left thigh",
  "inner right thigh",
  "front left knee",
  "front right knee",
  "left back of knee",
  "right back of knee",
  "outer left calf",
  "outer right calf",
  "inner left calf",
  "inner right calf",
  "left shin",
  "right shin",
  "left ankle",
  "right ankle",

  // Feet
  "left top of foot",
  "right top of foot",
  "left sole of foot",
  "right sole of foot",
  "left toes",
  "right toes",
  "left big toe",
  "right big toe",
  "left heel",
  "right heel",
  "left second toe",
  "left third toe",
  "left fourth toe",
  "left pinky toe",
  "right second toe",
  "right third toe",
  "right fourth toe",
  "right pinky toe",

  // Intimate area & Buttocks
  "left buttock",
  "right buttock",
  "left glute",
  "right glute",
  "between shoulder blades",
  "tailbone",
  "lumbar region",
  "left groin",
  "right groin",
  "middle lower abdomen",
  "intimate area (please describe precisely)",

  // Combination spots
  "above the heart",
  "below the collarbone",
  "between the ribs",
  "below the navel",
  "along the spine",
  "side of thigh",

  "frontal forehead",
  "frontal neck",
  "collarbone left",
  "collarbone right",
  "frontal chest",
  "frontal left chest",
  "frontal right chest",
  "frontal abdomen",
  "frontal upper abdomen",
  "frontal lower abdomen",
  "frontal navel",
  "frontal side abdomen ",
  "frontal side abdomen ",
  "frontal upper ",
  "frontal middle ",
  "frontal lower ",
  "frontal left ",
  "frontal right ",
  "frontal left ",
  "frontal right ",
  "frontal elbow ",
  "frontal elbow ",
  "frontal wrist ",
  "frontal wrist ",
  "frontal palm ",
  "frontal palm ",
  "frontal thigh ",
  "frontal thigh ",
  "frontal knee ",
  "frontal knee ",
  "frontal calf ",
  "frontal calf ",
  "frontal shin ",
  "frontal shin ",
  "frontal ankle ",
  "frontal ankle ",
  "frontal top of foot ",
  "frontal top of foot ",
  "frontal sole of foot ",
  "frontal sole of foot ",
  "frontal big toe ",
  "frontal big toe ",
  "frontal second toe ",
  "frontal second toe ",
  "frontal third toe ",
  "frontal third toe ",
  "frontal fourth toe ",
  "frontal fourth toe ",
  "frontal pinky toe ",
  "frontal pinky toe ",
  "frontal groin ",
  "frontal groin ",
  "frontal lower abdomen ",
];
