// Umfassende Liste möglicher Körperstellen für Tattoos (Richtung zuerst)
export const spotSuggestions = [
  // Kopf & Gesicht
  "Stirn",
  "linke Schläfe",
  "rechte Schläfe",
  "linke Wange",
  "rechte Wange",
  "linkes Ohr",
  "rechtes Ohr",
  "Ohrläppchen",
  "linker Kiefer",
  "rechter Kiefer",
  "Kinn",
  "Nase",
  "Augenbraue",
  "obere Lippe",
  "untere Lippe",
  "Hinterkopf",
  "Nacken",

  // Hals & Schlüsselbein
  "vorderer Hals",
  "seitlicher Hals links",
  "seitlicher Hals rechts",
  "linkes Schlüsselbein",
  "rechtes Schlüsselbein",
  "Kehlkopf",
  "Halswirbelsäule",

  // Brust & Bauch
  "Brust",
  "linke Brust",
  "rechte Brust",
  "unter der linken Brust",
  "unter der rechten Brust",
  "Brustbein",
  "Solarplexus",
  "Bauch",
  "oberer Bauch",
  "unterer Bauch",
  "Bauchnabel",
  "seitlicher Bauch links",
  "seitlicher Bauch rechts",

  // Rücken
  "oberer Rücken",
  "mittlerer Rücken",
  "unterer Rücken",
  "linke Rückenhälfte",
  "rechte Rückenhälfte",
  "Wirbelsäule",
  "Steißbein",
  "linkes Schulterblatt",
  "rechtes Schulterblatt",

  // Arme
  "äußerer linker Oberarm",
  "äußerer rechter Oberarm",
  "innerer linker Oberarm",
  "innerer rechter Oberarm",
  "äußerer linker Unterarm",
  "äußerer rechter Unterarm",
  "innerer linker Unterarm",
  "innerer rechter Unterarm",
  "linke Achsel",
  "rechte Achsel",
  "linker Ellenbogen",
  "rechter Ellenbogen",
  "linkes Handgelenk",
  "rechtes Handgelenk",
  "linker Handrücken",
  "rechter Handrücken",
  "linke Handfläche",
  "rechte Handfläche",
  "linker Daumen",
  "rechter Daumen",
  "alle Finger",
  "linker Zeigefinger",
  "linker Mittelfinger",
  "linker Ringfinger",
  "linker kleiner Finger",
  "rechter Zeigefinger",
  "rechter Mittelfinger",
  "rechter Ringfinger",
  "rechter kleiner Finger",

  // Beine
  "äußerer linker Oberschenkel",
  "äußerer rechter Oberschenkel",
  "innerer linker Oberschenkel",
  "innerer rechter Oberschenkel",
  "vorderes linkes Knie",
  "vorderes rechtes Knie",
  "linke Kniekehle",
  "rechte Kniekehle",
  "äußere linke Wade",
  "äußere rechte Wade",
  "innere linke Wade",
  "innere rechte Wade",
  "linkes Schienbein",
  "rechtes Schienbein",
  "linker Knöchel",
  "rechter Knöchel",

  // Füße
  "linker Fußrücken",
  "rechter Fußrücken",
  "linke Fußsohle",
  "rechte Fußsohle",
  "linke Zehen",
  "rechte Zehen",
  "linker großer Zeh",
  "rechter großer Zeh",
  "linke Ferse",
  "rechte Ferse",
  "linker zweiter Zeh",
  "linker dritter Zeh",
  "linker vierter Zeh",
  "linker kleiner Zeh",
  "rechter zweiter Zeh",
  "rechter dritter Zeh",
  "rechter vierter Zeh",
  "rechter kleiner Zeh",

  // Intimbereich & Gesäß
  "linkes Gesäß",
  "rechtes Gesäß",
  "linker Po",
  "rechter Po",
  "zwischen den Schulterblättern",
  "Steiß",
  "Lendenbereich",
  "linke Leiste",
  "rechte Leiste",
  "mittlerer Unterbauch",
  "intimer Bereich (bitte genau beschreiben)",

  // Kombinationsstellen
  "über dem Herzen",
  "unter dem Schlüsselbein",
  "zwischen den Rippen",
  "unterhalb des Bauchnabels",
  "entlang der Wirbelsäule",
  "seitlich am Oberschenkel",

  "frontale Stirn",
  "frontaler Hals",
  "Schlüsselbein links",
  "Schlüsselbein rechts",
  "frontale Brust",
  "frontale linke Brust",
  "frontale rechte Brust",
  "frontaler Bauch",
  "frontaler Oberbauch",
  "frontaler Unterbauch",
  "frontaler Bauchnabel",
  "frontaler seitlicher Bauch ",
  "frontaler seitlicher Bauch ",
  "frontaler oberer ",
  "frontaler mittlerer ",
  "frontaler unterer ",
  "frontaler linker ",
  "frontaler rechter ",
  "frontaler linker ",
  "frontaler rechter ",
  "frontaler Ellenbogen ",
  "frontaler Ellenbogen ",
  "frontales Handgelenk ",
  "frontales Handgelenk ",
  "frontale Handfläche ",
  "frontale Handfläche ",
  "frontaler Oberschenkel ",
  "frontaler Oberschenkel ",
  "frontales Knie ",
  "frontales Knie ",
  "frontale Wade ",
  "frontale Wade ",
  "frontales Schienbein ",
  "frontales Schienbein ",
  "frontaler Knöchel ",
  "frontaler Knöchel ",
  "frontaler Fußrücken ",
  "frontaler Fußrücken ",
  "frontale Fußsohle ",
  "frontale Fußsohle ",
  "frontaler großer Zeh ",
  "frontaler großer Zeh ",
  "frontaler zweiter Zeh ",
  "frontaler zweiter Zeh ",
  "frontaler dritter Zeh ",
  "frontaler dritter Zeh ",
  "frontaler vierter Zeh ",
  "frontaler vierter Zeh ",
  "frontaler kleiner Zeh ",
  "frontaler kleiner Zeh ",
  "frontale Leiste ",
  "frontale Leiste ",
  "frontaler Unterbauch ",
];
